workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 30
    environment:
      groups:
        - play_store
        - apple_store
        - personal_data
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - |
        # set up key.properties
        echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$FCI_KEYSTORE_PASSWORD
        keyPassword=$FCI_KEY_PASSWORD
        keyAlias=$FCI_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter config --enable-web
      - flutter config --enable-linux-desktop
      - flutter config --enable-macos-desktop
      - flutter build appbundle --release  --flavor production   --target lib/main_profile.dart
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "app.flutter.rushpuzzle" --type IOS_APP_STORE --platform=IOS --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --export-options-plist=/Users/builder/export_options.plist  --flavor
        production  --target lib/main_profile.dart
      - |
        # build web
        flutter build web --release --web-renderer html --flavor production  --target lib/main_profile.dart
        cd build/web
        7z a -r ../web.zip ./*
      - |
        # Publish only for tag builds
        if [ -z ${CM_TAG} ]; then
           echo "Not a tag build will not publish GitHub release"
        exit 0
        fi
        gh auth login --with-token <<<"${GITHUB_TOKEN}"
        gh release create "${CM_TAG}" \
            --title "Rush Puzzle ${CM_TAG}" \
            build/**/outputs/apk/**/*.apk  \
            build/**/outputs/bundle/**/*.aab  \
            build/**/outputs/**/mapping.txt \
            build/ios/ipa/*.ipa \
            /tmp/xcodebuild_logs/*.log \
            build/web.zip \
            '*.snap' \
            build/windows/**/*.msix \
            flutter_drive.log 
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/web.zip
      - '*.snap'
      - build/windows/**/*.msix
      - build/windows/**/*.exe
      - build/macos/**/*.pkg
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - git@jaimeblasco.com
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
        track: beta
        in_app_update_priority: 0
      app_store_connect:
        api_key: $APPLE_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
  desktop:
    name: macos
    max_build_duration: 30
    environment:
      groups:
        - play_store
        - apple_store
        - personal_data
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - flutter packages pub get
      - flutter config --enable-web
      - flutter config --enable-linux-desktop
      - flutter config --enable-macos-desktop
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "app.flutter.rushpuzzle"  --type MAC_APP_STORE --platform MAC_OS  --create
      - keychain add-certificates
      - xcode-project use-profiles
      - |
        # build macos
        flutter build macos --release --target lib/main_profile.dart
      - |    
        # create macos package
        set -x

          # Command to find the path to your generated app
          APP_NAME=$(find $(pwd) -name "*.app")
          cd $(dirname "$APP_NAME")
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg

          # Create an unsigned package
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

          # Find the installer certificate commmon name in keychain
          INSTALLER_CERT_NAME=$(keychain list-certificates \
            | jq '.[]
              | select(.common_name
              | contains("Mac Developer Installer"))
              | .common_name' \
            | xargs)

          # Sign the package
          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"          
      - |
        # Publish only for tag builds
        if [ -z ${CM_TAG} ]; then
           echo "Not a tag build will not publish GitHub release"
        exit 0
        fi

        gh auth login --with-token <<<"${GITHUB_TOKEN}"
        gh release create "${CM_TAG}" \
            build/macos/**/*.pkg \
            flutter_drive.log 
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/web.zip
      - '*.snap'
      - build/windows/**/*.msix
      - build/windows/**/*.exe
      - build/macos/**/*.pkg
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - git@jaimeblasco.com
      app_store_connect:
        api_key: $APPLE_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
  windows-release-workflow:
    name: Windows release workflow
    instance_type: windows_x2
    max_build_duration: 60
    environment:
      groups:
        - windows-signing 
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Configure for Windows
        script: flutter config --enable-windows-desktop
      - name: Build Windows
        script: flutter build windows
      # 1. You should have `msix` dependency under `dev_dependencies` section in pubspec.yaml.
      # 2. If you have defined the MSIX build configurations inside the pubspec.yaml, 
      #    then you can just use "msix:create" without passing any parameters.
      #    [NOTE: This project has the configurations defined in the pubspec.yaml file]
      - name: Package Windows
        script: flutter pub run msix:create
      # If you don't have the configurations created inside pubspec.yaml, then you need 
      # to pass the configurations as parameters. Use the following script in that case:
      # ----------------------------------------------------------------------------------
      # - name: Package Windows
      #   script: |
      #     flutter pub add msix
      #     flutter pub run msix:create --display-name='<AppName>' --publisher-display-name='<PublisherName>' --publisher='<PublisherID>' --identity-name='<PublisherName.AppName>' --version=1.0.0.0 --logo-path='./logo/<file_name.png>' --store=true
      # ----------------------------------------------------------------------------------
      - |
        # Publish only for tag builds
        if [ -z ${CM_TAG} ]; then
           echo "Not a tag build will not publish GitHub release"
        exit 0
        fi
        gh auth login --with-token <<<"${GITHUB_TOKEN}"
        gh release create "${CM_TAG}" \
            --title "Rush Puzzle ${CM_TAG}" \
            build/windows/**/*.msix
    artifacts:
      - build/windows/**/*.msix
    publishing:
      partner_center:
        store_id: $AZ_STORE_ID # <-- You can find the `store_id` inside your Partner Center app by going to [Product management > Product Identity].
        tenant_id: $AZ_TENANT_ID # <-- You will get `tenant_id` from the Azure AD Overview page.
        client_id: $AZ_CLIENT_ID # <-- You will also get `client_id` from the Azure AD Overview page.
        client_secret: $PARTNER_CLIENT_SECRET # <-- `client_secret` is retrieved from the application environment variable
      email:
        recipients:
          - email@example.com