name: rush_hour_puzzle
description: Play a daily Rush Puzzle game
version: 0.0.9+9
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  fireworks:
    path: packages/fireworks
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  puzzle_models:
    path: packages/puzzle_models
  puzzles_repository:
    path: packages/puzzles_repository
  share_plus: ^3.1.0
  z_cubic_text:
    path: packages/z_cubic_text
  zclouds:
    path: packages/zclouds
  zcomponents:
    path: packages/zcomponents


dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  msix: ^3.3.2
  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: Rush App
  publisher_display_name: Jaime Blasco Andrés
  logo_path: .\windows\logo.png
  capabilities: internetClient
  store: true