name: z_cubic_text
description: Collection of cubic letters made with ZFlutter.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  zflutter:
    git: 
      url: https://github.com/jamesblasco/zflutter
      path: zflutter
      ref: bde6f320d6d278a82f40420df68a1ab4c466ba4c

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
