name: zcomponents
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable:
  flutter:
    sdk: flutter
  provider:
  vector_math: 
  zflutter:
    git: 
      url: https://github.com/jamesblasco/zflutter
      path: zflutter
      ref: null_safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0