name: fireworks
description: Package for displaying virtual fireworks in Flutter.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.2.0

dev_dependencies:
  pedantic: ^1.11.0
