// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-cSR-CC4IvKZKdPaXYzEZ4_rWQRKBoE',
    appId: '1:1041926528718:web:6111018d26ebe70a19fa9f',
    messagingSenderId: '1041926528718',
    projectId: 'flutter-rush',
    authDomain: 'flutter-rush.firebaseapp.com',
    storageBucket: 'flutter-rush.appspot.com',
    measurementId: 'G-M09PGRLCJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTVLwzLY3WkRnKK7p36OFd0aImuWEZ_Q',
    appId: '1:1041926528718:android:e34845c71d09020c19fa9f',
    messagingSenderId: '1041926528718',
    projectId: 'flutter-rush',
    storageBucket: 'flutter-rush.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnChv2vIIXIcDug8SIhVBgrmBcHZWyMWE',
    appId: '1:1041926528718:ios:8136dbb8a0635b9919fa9f',
    messagingSenderId: '1041926528718',
    projectId: 'flutter-rush',
    storageBucket: 'flutter-rush.appspot.com',
    iosClientId: '1041926528718-pqsds9desbjlgo7crtsesdf0ac6i5eje.apps.googleusercontent.com',
    iosBundleId: 'app.flutter.rushpuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnChv2vIIXIcDug8SIhVBgrmBcHZWyMWE',
    appId: '1:1041926528718:ios:8136dbb8a0635b9919fa9f',
    messagingSenderId: '1041926528718',
    projectId: 'flutter-rush',
    storageBucket: 'flutter-rush.appspot.com',
    iosClientId: '1041926528718-pqsds9desbjlgo7crtsesdf0ac6i5eje.apps.googleusercontent.com',
    iosBundleId: 'app.flutter.rushpuzzle',
  );
}
