name: puzzles_repository
description: Repository that handles puzzles related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  puzzle_models:
    path: ../puzzle_models

dev_dependencies:
  flutter_test:
    sdk: flutter  
  test: ^1.19.2
  very_good_analysis: ^2.4.0

flutter:
  assets:
    - assets/