name: puzzle_models
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0



dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  test: ^1.19.2
  very_good_analysis: ^2.4.0
